language: php
# we seem to need the old trusty dist otherwise communication with jackrabbit fails
dist: trusty

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: COMPOSER_OPTIONS=--prefer-lowest --prefer-stable

before_script:
  - composer update --prefer-dist ${COMPOSER_OPTIONS}
  - ./bin/jackrabbit.sh

script: vendor/bin/phpunit

notifications:
  irc: "irc.freenode.org#jackalope"
